# Generated by Django 3.2.8 on 2021-10-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211012_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subimage',
            old_name='Product',
            new_name='product',
        ),
    ]
